from django.db import transaction
from django.contrib.auth.models import User, Group
from .models import ForceReset, Suppliers, Teams, Reagents, Internal, Validation, Recipe, Inventory, Solutions, VolUsage
from decimal import Decimal

def ADD_CYTO():
    with transaction.atomic():
        suppliers = 0
        reagents = 0
        sups=["Cytocell",
              "Leica Microsystems UK",
              "Abbott Laboratories Ltd",
              "Generon",  
              ]
        for sup in sups:
            if not Suppliers.objects.filter(name=sup).exists():
                Suppliers.create(sup)
                suppliers+=1
        for name, cata, sup, minimum, vol, team in (("Fast13,21 Probe Cytocell [100ul]","LPF003","Cytocell","30",True,"CYTO"),
                                                    ("MALT1 Breakapart Probe Cytocell [100ul]","LPS017","Cytocell","30",True,"CYTO"),
                                                    ("FGFR1 Breakapart Probe Cytocell [100ul]","LPS018","Cytocell","30",True,"CYTO"),
                                                    ("IGH/MAFB Translocation, Dual fusion Probe Cytocell [100ul]","LPH044","Cytocell","30",True,"CYTO"),
                                                    ("IGH/MAFB Plus Translocation, Dual fusion Probe Cytocell [100ul]","LPH077","Cytocell","30",True,"CYTO"),
                                                    ("CKS1B/CDKN2C (P18) Amplfication/Deletion Probe Cytocell [100ul]","LPH039","Cytocell","30",True,"CYTO"),
                                                    ("FAST PML/RARA Translocation, Dual fusion Probe Cytocell [100ul]","LPH064","Cytocell","30",True,"CYTO"),
                                                    ("TCRAD Breakapart Probe Cytocell [100ul]","LPH047","Cytocell","30",True,"CYTO"),
                                                    ("TCRAD Breakapart Probe Cytocell [50ul]","LPH047-S","Cytocell","10",True,"CYTO"),
                                                    ("TCRB Breakapart Probe Cytocell [100ul]","LPH048","Cytocell","30",True,"CYTO"),
                                                    ("TCRB Breakapart Probe Cytocell [50ul]","LPH048-S","Cytocell","10",True,"CYTO"),
                                                    ("TLX1 Breakapart Probe Cytocell [100ul]","LPH049","Cytocell","30",True,"CYTO"),
                                                    ("TLX1 Breakapart Probe Cytocell [50ul]","LPH049-S","Cytocell","10",True,"CYTO"),
                                                    ("TLX3 Breakapart Probe Cytocell [100ul]","LPH050","Cytocell","30",True,"CYTO"),
                                                    ("TLX3 Breakapart Probe Cytocell [50ul]","LPH050-S","Cytocell","10",True,"CYTO"),
                                                    ("SHOX Probe Cytocell [50ul]","LPU25-S","Cytocell","10",True,"CYTO"),
                                                    ("E2A breakapart Probe Cytocell [50ul]","LPH019-S","Cytocell","10",True,"CYTO"),
                                                    ("P53/ATM Probe Combination Cytocell [100ul]","LPH052","Cytocell","30",True,"CYTO"),
                                                    ("P53 Deletion Probe Cytocell [100ul]","LPS037","Cytocell","30",True,"CYTO"),
                                                    ("CSF1R Breakapart Probe Cytocell [100ul]","MPH2870","Cytocell","30",True,"CYTO"),
                                                    ("ABL2 Breakapart Probe Cytocell [100ul]","MPH2850","Cytocell","30",True,"CYTO"),
                                                    ("ABL1 Breakapart Probe Cytocell [100ul]","MPH2840","Cytocell","30",True,"CYTO"),
                                                    ("PDGFRA Breakapart Probe Cytocell [100ul] ","MPH0230","Cytocell","30",True,"CYTO"),
                                                    ("PDGFRB Breakapart Probe Cytocell [100ul] ","LPH031","Cytocell","30",True,"CYTO"),
                                                    ("FLI1/EWSR1 Translocation Dual Fusion Probe Cytocell [50ul]","LPS007-S","Cytocell","10",True,"CYTO"),
                                                    ("EWSR1/ERG Translocation, Dual Fusion Probe Cytocell [50ul]","LPS008-S","Cytocell","10",True,"CYTO"),
                                                    ("BCL2 Breakapart Probe Cytocell [100ul]","LPS028","Cytocell","30",True,"CYTO"),
                                                    ("TFE3 Breakapart Probe Cytocell [100ul]","RU-LPS051","Cytocell","30",True,"CYTO"),
                                                    ("BCR/ABL Plus Translocation Dual Fusion Probe Cytocell [100ul]","LPH038","Cytocell","30",True,"CYTO"),
                                                    ("EWSR1 Breakapart Probe Cytocell [100ul]","LPS006","Cytocell","30",True,"CYTO"),
                                                    ("Del (7q) Plus Cytocell [100ul]","MPH13880","Cytocell","30",True,"CYTO"),
                                                    ("21qter Subtelomere Specific Probe Green Cytocell[50ul]","LPT21QG","Cytocell","10",True,"CYTO"),
                                                    ("IGL Breakapart Probe Cytocell [50ul] ","LPS039-S","Cytocell","10",True,"CYTO"),
                                                    ("IGK Breakapart Probe Cytocell [50ul] ","LPS038-S","Cytocell","10",True,"CYTO"),
                                                    ("IGK/IGL/MYC Dual Fusion Probe Cytocell [100ul]","MPP4350","Cytocell","30",True,"CYTO"),
                                                    ("Del (5q) Plus Deletion Probe Cytocell [100ul]","MPH17010","Cytocell","30",True,"CYTO"),
                                                    ("CDK4 (with red) probe Cytocell [100ul]","MPP2640","Cytocell","30",True,"CYTO"),
                                                    ("NUP214/DEK Cytocell [100ul] ","MPH4290","Cytocell","30",True,"CYTO"),
                                                    ("IGH/CCND1 Translocation, Dual Fusion Probe Haemotology Cytocell [100ul]","LPH021","Cytocell","30",True,"CYTO"),
                                                    ("CHOP Breakapart Probe Cytocell [100ul]","LPS015","Cytocell","30",True,"CYTO"),
                                                    ("CHOP Breakapart Probe Cytocell [50ul]","LPS015-S","Cytocell","10",True,"CYTO"),
                                                    ("MLL Breakapart Probe Cytocell [100ul]","LPS013","Cytocell","30",True,"CYTO"),
                                                    ("CDK4 Probe Leica [100ul]","KBI-10725","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("Enk/NUP214 Probe Leica [100ul]","KBI-10306","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("KMT2A/AFF1 Probe Leica [100ul]","KBI-10404","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("MECOM Probe Leica [100ul]","KBI- 10205","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("MYCN Probe Leica [100ul]","KBI-10706","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("NUP98 Probe Leica [100ul]","KBI-10311","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("SE 1 (1qh) Blue Probe Leica [20ul]","KBI-20001B","Leica Microsystems UK","5",True,"CYTO"),
                                                    ("SE 2 (D2Z) Green Probe Leica [20ul]","KBI-20002G","Leica Microsystems UK","5",True,"CYTO"),
                                                    ("SE 12 (D12Z3) Blue Probe Leica [20ul]","KBI-20012B","Leica Microsystems UK","5",True,"CYTO"),
                                                    ("SE 15 (D15Z) Blue Probe Leica [20ul]","KBI-20015B","Leica Microsystems UK","5",True,"CYTO"),
                                                    ("USP6 Probe Leica [100ul]","KBI-00094","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("5q- Probe Leica [100ul]","KBI-10210","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("7q- Probe Leica [100ul]","KBI-10207","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("20q- Probe Leica [100ul]","KBI-10203","Leica Microsystems UK","30",True,"CYTO"),
                                                    ("ALK Breakapart Probe Vysis [200ul]","06N38-023","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("LSI PML/RARA Probe Vysis [20ul]","01N63-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("MYC Breakapart Probe Vysis [20ul]","01N63-20","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("ETV6 Breakapart Probe Vysis [20ul]","04N09-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("TRA/D Breakapart Probe Vysis[20ul]","05N41-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("CBFB Breakapart Probe Vysis [20ul]","05N44-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("ASS/ 9q34 SpectrumAqua Probe Vysis[20ul]","05N53-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("BRC/ABL Probe Vysis[20ul]","08L10-002","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("MLL Breakapart Probe Vysis[20ul]","08L57-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("IGH/BCL2 Probe Vysis [20ul]","08L60-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("IGH Breakapart Probe Vysis [20ul]","08L63-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("RUNX1/RUN1T1 DF Probe Vysis [20ul]","08L70-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("MDM2/CEP12 Probe Vysis [20ul]","01N15-010","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("FUS Breakapart Probe Vysis [20ul]","03N58-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("EWSR1 Breakapart Probe Vysis [20ul]","03N59-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("SS18 Breakapart Probe Vysis [20ul]","03N61-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("SRY/CEPX Probe Vysis [20ul]","06N29-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("STS probe Vysis [20ul]","05J28-004","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("SNRPN Probe Vysis [20ul]","06N27-010","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("TUPLE 1 Probe Vysis [20ul]","08L59-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("BCL6 Breakapart Vysis [20ul]","01N23-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("CKDN2A Probe Vysis [20ul]","04N61-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("ETV6/RUNX1 Breakapart Probe Vysis [20ul]","08L66-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("RARA Breakapart Probe Vysis [20ul]","05J25-003","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("PML/RARA Probe Vysis [20ul]","01N36-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("EGR1 Probe Vysis [20ul]","08L68-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("FOXO1 (FKHR) Breakapart Probe Vysis [20ul]","03N60-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("PDGFRB Breakapart Probe Vysis [20ul]","06N24-010","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("IGH/FGFR3 Probe Vysis [20ul]","01N69-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("IGH/CCND1 Probe Vysis [20ul]","05N33-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("IGH/MAF Probe Vysis [20ul]","05N32-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("PDGFRA* Probe Vysis[20ul]","05N52-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("CHOP Breakapart Probe Vysis [20ul]","03N57-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("1 Centromere Red Probe Vysis [20ul]","6J36-001","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("2 Centromere Red Probe Vysis [20ul]","6J36-027","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("3 Centromere Red Probe Vysis [20ul]","6J36-003","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("4 Centromere Red Probe Vysis [20ul]","6J36-004","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("4 Centromere Aqua Probe Vysis [20ul]","6J54-004","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("4 Centromere Green Probe Vysis [20ul]","6J37-004","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("6 Centromere Red Probe Vysis [20ul]","6J36-006","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("6 Centromere Aqua Probe Vysis [20ul]","6J54-006","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("6 Centromere Green Probe Vysis [20ul]","6J37-006","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("7 Centromere Red Probe Vysis [20ul]","6J36-007","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("7 Centromere Aqua Probe Vysis [20ul]","6J54-007","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("7 Centromere Green Probe Vysis [20ul]","6J37-007","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("8 Centromere Green Probe Vysis [20ul]","6J37-008","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("8 Centromere Aqua Probe Vysis [20ul]","6J54-008","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("8 Centromere Red Probe Vysis [20ul]","7J20-008","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("9 Centromere Red Probe Vysis [20ul]","6J36-009","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("9 Centromere Aqua Probe Vysis [20ul]","6J54-009","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("9 Centromere Green Probe Vysis [20ul]","6J37-009","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("10 Centromere Red Probe Vysis [20ul]","6J36-010","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("10 Centromere Aqua Probe Vysis [20ul]","6J54-010","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("10 Centromere Green Probe Vysis [20ul]","6J37-010","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("11 Centromere Red Probe Vysis [20ul]","6J36-011","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("11 Centromere Aqua Probe Vysis [20ul]","6J54-011","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("11 Centromere Green Probe Vysis [20ul]","6J37-011","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("12 Centromere Red Probe Vysis [20ul]","7J20-012","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("12 Centromere Green Probe Vysis [20ul]","6J37-012","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("15 Centromere Aqua Probe Vysis [20ul]","6J54-015","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("15 Centromere Green Probe Vysis [20ul]","6J37-015","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("15 Centromere Red Probe Vysis [20ul]","6J36-015","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("16 Centromere Aqua Probe Vysis [20ul]","5J09-016","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("16 Centromere Green Probe Vysis [20ul]","5J10-016","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("16 Centromere Red Probe Vysis [20ul]","5J08-016","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("17 Centromere Aqua Probe Vysis [20ul]","6J38-017","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("17 Centromere Green Probe Vysis [20ul]","6J37-017","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("17 Centromere Red Probe Vysis [20ul]","6J36-017","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("18 Centromere Aqua Probe Vysis [20ul]","5J09-018","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("18 Centromere Green Probe Vysis [20ul]","5J10-018","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("18 Centromere Red Probe Vysis [20ul]","5J08-018","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("20 Centromere Red Probe Vysis [20ul]","6J36-020","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("22 Centromere Green Probe Vysis [20ul]","5J17-024","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("X Centromere Aqua Probe Vysis [20ul]","5J09-023","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("X Centromere Green Probe Vysis [20ul]","5J10-023","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("X Centromere Red Probe Vysis [20ul]","5J08-023","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("X Centromere Red and Y Centromere Green Probe Vysis [20ul]","7J20-050","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("X and Y Red Probe Vysis [20ul]","5J10-051","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("Y Centromere Aqua Probe Vysis [20ul]","5J09-024","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("Y Centromere Green Probe Vysis [20ul]","5J10-024","Abbott Laboratories Ltd","5",True,"CYTO"),
                                                    ("1p Telomere Green Probe Vysis [5ul]","5J03-001","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("1q Telomere Red Probe Vysis [5ul]","5J04-001","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("2p Telomere Green Probe Vysis [5ul]","5J03-002","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("2q Telomere Red Probe Vysis [5ul]","5J04-002","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("3p Telomere Green Probe Vysis [5ul]","5J03-003","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("3q Telomere Red Probe Vysis [5ul]","5J04-003","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("4p Telomere Green Probe Vysis [5ul]","5J03-004","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("4q Telomere Red Probe Vysis [5ul]","5J04-004","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("5p Telomere Green Probe Vysis [5ul]","5J03-005","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("5q Telomere Red Probe Vysis [5ul]","5J04-005","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("6p Telomere Green Probe Vysis [5ul]","5J03-006","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("6q Telomere Red Probe Vysis [5ul]","5J04-006","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("7p Telomere Green Probe Vysis [5ul]","5J03-007","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("7q Telomere Red Probe Vysis [5ul]","5J04-007","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("8p Telomere Green Probe Vysis [5ul]","5J03-008","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("8q Telomere Red Probe Vysis [5ul]","5J04-008","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("9p Telomere Green Probe Vysis [5ul]","5J03-009","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("9q Telomere Red Probe Vysis [5ul]","5J04-009","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("10p Telomere Green Probe Vysis [5ul]","5J03-010","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("10q Telomere Orange Probe Vysis [5ul]","5J04-010","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("11p Telomere Green Probe Vysis [5ul]","5J03-011","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("11q Telomere Red Probe Vysis [5ul]","5J04-011","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("12p Telomere Green Probe Vysis [5ul]","5J03-012","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("12q Telomere Red Probe Vysis [5ul]","5J04-012","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("13q Telomere Red Probe Vysis [5ul]","5J04-013","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("14q Telomere Red Probe Vysis [5ul]","5J04-014","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("15q Telomere Red Probe Vysis [5ul]","5J04-015","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("16p Telomere Green Probe Vysis [5ul]","5J03-016","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("16q Telomere Red Probe Vysis [5ul]","5J04-016","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("17p Telomere Green Probe Vysis [5ul]","5J03-017","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("17q Telomere Red Probe Vysis [5ul]","5J04-017","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("18P Telomere Green Probe Vysis [5ul]","5J03-018","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("18q Telomere Red Probe Vysis [5ul]","5J04-018","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("19p Telomere Green Probe Vysis[5ul]","5J03-019","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("19q Telomere Red Probe Vysis [5ul]","5J04-019","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("20p Telomere Green Probe Vysis [5ul]","5J03-020","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("20q Telomere Red Probe Vysis [5ul]","5J04-020","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("21q Telomere Red Probe Vysis [5ul]","5J04-021","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("22q Telomere Red Probe Vysis [5ul]","5J04-022","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("XpYp Telomere Green Probe Vysis [5ul]","5J03-023","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("XqYq Telomere Red Probe Vysis [5ul]","5J04-023","Abbott Laboratories Ltd","1.5",True,"CYTO"),
                                                    ("MAML2 Breakapart Probe ZytoLight [200ul]","Z-2014-200","Generon","30",True,"CYTO"),
                                                    ("MAML2 Breakapart Probe ZytoLight [50ul]","Z-2014-50","Generon","10",True,"CYTO"),
                                                    ("ERBB2 Probe ZytoLight [200ul]","Z-2015-200","Generon","30",True,"CYTO"),
                                                    ("FOXO1/PAX3 Dual Fusion Probe ZytoLight [50ul]","Z-2018-50","Generon","10",True,"CYTO"),
                                                    ("FOXO1/PAX7 Dual Fusion Probe ZytoLight [50ul]","Z-2019-50","Generon","10",True,"CYTO"),
                                                    ("FHIT Probe ZytoLight [50ul]","Z-2062-50","Generon","10",True,"CYTO"),
                                                    ("VHL Probe ZytoLight [50ul]","Z-2084-50","Generon","10",True,"CYTO"),
                                                    ("CDK4 Probe ZytoLight [50ul]","Z-2103-50","Generon","10",True,"CYTO"),
                                                    ("TFE3 Breakapart Probe ZytoLight [50ul]","Z-2109-50","Generon","10",True,"CYTO"),
                                                    ("COL1A1/PDGFB Dual Fusion Probe ZytoLight [50ul]","Z-2116-50","Generon","10",True,"CYTO"),
                                                    ("MYB Breakapart Probe ZytoLight [50ul]","Z-2143-50","Generon","10",True,"CYTO"),
                                                    ("ROS1 Breakapart Probe ZytoLight [200ul]","Z-2144-200","Generon","30",True,"CYTO"),
                                                    ("NR4A3 Breakpart Probe ZytoLight [50ul]","Z-2145-50","Generon","10",True,"CYTO"),
                                                    ("TP53/ATM Probe ZytoLight [200ul]","Z-2159-200","Generon","30",True,"CYTO"),
                                                    ("YWHAE Breakapart Probe ZytoLight [50ul]","Z-2175-50","Generon","10",True,"CYTO"),
                                                    ("TP53/MPO (TP53/17q22) Probe ZytoLight [50ul]","Z-2198-50","Generon","10",True,"CYTO"),
                                                    ("NTRK3 Breakapart Probe ZytoLight [50ul]","Z-2206-50","Generon","10",True,"CYTO"),
                                                    ("NUTM1 Breakapart Probe ZytoLight [50ul]","Z-2208-50","Generon","10",True,"CYTO"),
                                                    ("11q Probe ZytoLight [50ul]","Z-2216-50","Generon","10",True,"CYTO")):
            values={}
            values["name"]=name
            values["cat_no"]=cata
            try:
                values["supplier_def"]=Suppliers.objects.get(name=sup)
                values["team_def"]=Teams.objects.get(name=team)
            except Exception as e:
                print(e)
                print(sup)
                import pdb; pdb.set_trace()
            values["min_count"]=Decimal(minimum)
            values["track_vol"]=vol
            try:
                Reagents.create(values)
                reagents+=1
            except Exception as e:
                print(e)
                print(name)
                import pdb; pdb.set_trace()
        return suppliers, reagents
