from django.db import transaction
from django.contrib.auth.models import User, Group
from .models import ForceReset, Suppliers, Reagents, Internal, Validation, Recipe, Inventory, Solutions, CytoUsage

def PRIME():
    with transaction.atomic():
        User_Mod = Group.objects.create(name="User_Mod")
        perms=['13','14','16','8','5','6','9','10','12']
        for p in perms:
            User_Mod.permissions.add(p)
        Non_SU_Admin = Group.objects.create(name="Non_SU_Admin")
        perms2=['1','2','4','5','6','8','9','10','12','13','14','16','17','18','19','21','22','23','24']
        for p2 in perms2:
            Non_SU_Admin.permissions.add(p2)
        #password fine in here as after first log on required to change it
        user = User.objects.create_user("Admin", "", "password")
        user.first_name = ""
        user.last_name = ""
        user.is_superuser=True
        user.is_staff=True
        user.save()
        sups=["Agilent Technologies",
        "Applied Biosystems",
        "Beckman Coulter",
        "Bioline",
        "Bio-Rad",
        "Clent Life Science",
        "DNA Genotek",
        "Elucigene Diagnostics",
        "Fisher Scientific",
        "Illumina",
        "Launch Diagnostics",
        "Life Technologies",
        "MRC Holland",
        "New England BioLabs",
        "Promega",
        "Qiagen",
        "Roche Diagnostic",
        "Sigma-Aldrich",
        "Scientific Laboratory Supplies",
        "Sophia Genetics",
        "TaKaRa Clontech",
        "TWIST Bioscience",
        "VH Bio",
        "VWR International"]
        for sup in sups:
            Suppliers.create(sup)
        for name, cata, sup, minimum, cyto in (('Agarose Medium EEO~', 'A6877', 'Sigma-Aldrich', '3', False),
                                               ('0.5M EDTA pH8.0~', 'AM9261', 'Life Technologies', '1', False),
                                               ('SALSA MLPA EK20 Reagent Kit', 'EK20-FAM', 'MRC Holland', '1', False),
                                               ('S4 Sample Stabiliser', 'SMR04', 'MRC Holland', '3', False),
                                               ('SALSA HhaI', 'SMR50', 'MRC Holland', '1', False),
                                               ('GeneScan 500 LIZ Dye Size Standard~', '4322682', 'Life Technologies', '2', False),
                                               ('GeneScan 600 LIZ Dye Size Standard~', '4366589', 'Life Technologies', '1', False),
                                               ('Hi-Di Formamide~', '4311320', 'Life Technologies', '2', False),
                                               ('Devyser CFTR combo Core + UK', '8-A603', 'Launch Diagnostics', '2', False),
                                               ('AmplideX PCR FMR1 Kit', '676008', 'VH Bio', '1', False),
                                               ('AmplideX PCR FMR1 Process Control', '649513', 'VH Bio', '1', False),
                                               ('AmpFLSTR Identifiler PCR Amplification kit', '4322288', 'Life Technologies', '1', False),
                                               ('AmpliTaq Gold DNA Polymerase with Buffer II and MgCl2', 'N8080241', 'Life Technologies', '1', False),
                                               ('Pwo DNA Polymerase', '11644955001', 'Sigma-Aldrich', '1', False),
                                               ('Megamix-Blue', '2MMB-5', 'Clent Life Science', '1', False),
                                               ('TaKaRa LA Taq DNA Polymerase Hot-start Version', 'RR042B', 'TaKaRa Clontech', '2', False),
                                               ('QIAGEN Multiplex PCR Kit', '206145', 'Qiagen', '1', False),
                                               ('T4 DNA Ligase', '15224025', 'Life Technologies', '1', False),
                                               ('ApaI Restriction Enzyme', '10703753001', 'Sigma-Aldrich', '1', False),
                                               ('DNA Molecular Weight Marker II', '10236250001', 'Sigma-Aldrich', '1', False),
                                               ('BglI Restriction Enzyme', 'ER0071', 'Life Technologies', '1', False),
                                               ('HpaII Restriction Enzyme', 'R0171S', 'New England BioLabs', '1', False),
                                               ('HaeIII Restriction Enzyme', 'R0108S', 'New England BioLabs', '1', False),
                                               ('BclI Restriction Enzyme', 'R0160S', 'New England BioLabs', '1', False),
                                               ('RsaI Restriction Enzyme', 'R0167L', 'New England BioLabs', '1', False),
                                               ('MboI Restriction Enzyme', 'R0147L', 'New England BioLabs', '1', False),
                                               ('Hi-Strength Analytical Agarose~', 'H15669', 'Scientific Laboratory Supplies', '1', False),
                                               ('PfuUltraII Fusion HotStart DNA Polymerase', '600670', 'Qiagen', '1', False),
                                               ('Taq DNA Polymerase', '11146173001', 'Sigma-Aldrich', '1', False),
                                               ("O'RangeRuler 100 bp DNA Ladder", 'SM0623', 'Life Technologies', '1', False),
                                               ('Quick-Load Purple 50 bp DNA Ladder', 'N0556S', 'New England BioLabs', '1', False),
                                               ('HindIII Restriction enzyme', 'R0104S', 'New England BioLabs', '1', False),
                                               ('TaqMan Gene Expression Master Mix', '4369016', 'Life Technologies', '1', False),
                                               ('PyroMark Gold Q96 Reagents', '972804', 'Qiagen', '1', False),
                                               ('PyroMark Denaturation Solution', '979007', 'Qiagen', '2', False),
                                               ('PyroMark Wash Buffer', '979008', 'Qiagen', '1', False),
                                               ('PyroMark Annealing Buffer', '979009', 'Qiagen', '1', False),
                                               ('Sreptavidin Sepharose High Performance', '17-5113-01', 'VWR International', '1', False),
                                               ('Megamix Royal', '2MMR-50', 'Clent Life Science', '1', False),
                                               ('BigDye Terminator v3.1 Cycle Sequencing Kit', '4337457', 'Life Technologies', '0', False),
                                               ('High Sensitivity D1000 ScreenTape~', '5067-5584', 'Agilent Technologies', '2', False),
                                               ('Genomic DNA ScreenTape~', '5067-5365', 'Agilent Technologies', '0', False),
                                               ('Genomic DNA Reagents~', '5067-5366', 'Agilent Technologies', '0', False),
                                               ('High Sensitivity D1000 Reagents~', '5067-5585', 'Agilent Technologies', '2', False),
                                               ('Ampure XP', 'A63882', 'Beckman Coulter', '0', False),
                                               ('CleanSeq', 'A29161', 'Beckman Coulter', '0', False),
                                               ('POP-7 Polymer~', '4363935', 'Life Technologies', '2', False),
                                               ('AluI Restriction Enzyme', 'FD0014', 'Life Technologies', '1', False),
                                               ('3730 Buffer with EDTA~', '4335613', 'Life Technologies', '0', False),
                                               ('3730 DNA Analyzer Capillary Array~', '4331250', 'Life Technologies', '1', False),
                                               ('Maxwell RSC Blood DNA Kit', 'AS1400', 'Promega', '3', False),
                                               ('SALSA P200 Reference MLPA kit - 100 Reactions', 'PbP200-100R', 'MRC Holland', '1', False),
                                               ('KAPA2G Fast HotStart ReadyMix', 'KK5609', 'Sigma-Aldrich', '14', False),
                                               ('MiSeq Reagent Kit v3~', 'MS-102-3003', 'Illumina', '6', False),
                                               ('SALSA P310 TCOF MLPA kit - 100 Reactions', 'PbP310-100R', 'MRC Holland', '0', False),
                                               ('SALSA P229 OPA1 MLPA kit - 50 Reactions', 'PbP229-50R', 'MRC Holland', '0', False),
                                               ('PCR DIG Probe Synthesis Kit', '11636090910', 'Sigma-Aldrich', '0', False),
                                               ('Nextera XT Index kit v2 set B', 'FC-131-2002', 'Illumina', '0', False),
                                               ('Nextera XT Library Preparation Kit', 'FC-131-1096', 'Illumina', '0', False),
                                               ('DIG-High Prime', '11585606910', 'Sigma-Aldrich', '0', False),
                                               ('DIG Wash and Block Buffer Set', '11585762001', 'Sigma-Aldrich', '0', False),
                                               ('SALSA P279 CACNA1A MLPA kit - 50 Reactions', 'PbP279-50R', 'MRC Holland', '0', False),
                                               ('SALSA P152 ABCA4 MLPA kit - 50 Reactions', 'PbP152-50R', 'MRC Holland', '0', False),
                                               ('SALSA P108 SCN5A MLPA kit - 50 Reactions', 'PbP108-50R', 'MRC Holland', '0', False),
                                               ('SALSA P168 ARVC MLPA kit - 100 Reactions', 'PbP168-100R', 'MRC Holland', '0', False),
                                               ('SALSA P002 BRCA1 MLPA kit - 100 Reactions', 'PbP002-100R', 'MRC Holland', '0', False),
                                               ('SALSA P226 SDH MLPA kit - 50 Reactions', 'PbP226-50R', 'MRC Holland', '0', False),
                                               ('SALSA P048 LMNA MLPA kit - 50 Reactions', 'PbP048-50R', 'MRC Holland', '0', False),
                                               ('SALSA P427 PDHA1 MLPA kit - 50 Reactions', 'PbP427-50R', 'MRC Holland', '0', False),
                                               ('SALSA P387 NPHP1 MLPA kit - 100 Reactions', 'PbP387-100R', 'MRC Holland', '0', False),
                                               ('CF29v2', 'CF029B2', 'Elucigene Diagnostics', '0', False),
                                               ('Maxwell RSC FFPE DNA kit', 'AS1450', 'Promega', '0', False),
                                               ('SALSA P151 ABCA4 MLPA kit - 50 Reactions', 'PbP151-50R', 'MRC Holland', '0', False),
                                               ('SALSA MLPA EK5 Reagent Kit', 'EK5-FAM', 'MRC Holland', '1', False),
                                               ('SALSA P048 LMNA MLPA kit - 100 Reactions', 'PbP048-100R', 'MRC Holland', '0', False),
                                               ('SALSA P466 CDC73 MLPA kit - 100 Reactions', 'PbP466-100R', 'MRC Holland', '0', False),
                                               ('SALSA P179 LIMB1 MLPA kit - 50 Reactions', 'PbP179-50R', 'MRC Holland', '0', False),
                                               ('SALSA ME028 PWS/AS MLPA kit - 100 Reactions', 'ME028-100R', 'MRC Holland', '0', False),
                                               ('SALSA P090 BRCA2 MLPA kit - 100 Reactions', 'PbP090-100R', 'MRC Holland', '0', False),
                                               ('SALSA P213 HSP-2 MLPA kit - 25 Reactions', 'PbP213-25R', 'MRC Holland', '0', False),
                                               ('SALSA ME011 MMR MLPA kit - 100 Reactions', 'ME011-100R', 'MRC Holland', '0', False),
                                               ('SALSA P003-MSH2/MLH1 MLPA Kit - 100 Reactions', 'P003-100R', 'MRC Holland', '0', False),
                                               ('Trizma Base~', '11814273001', 'Sigma-Aldrich', '0', False),
                                               ('Anti-Digoxigenin-AP Fab Fragments', '11093274910', 'Sigma-Aldrich', '0', False),
                                               ('Bromophenol Blue~', '114391-5g', 'Sigma-Aldrich', '0', False),
                                               ('SALSA P016 VHL MLPA kit - 25 Reactions', 'PbP016-25R', 'MRC Holland', '0', False),
                                               ('SALSA P043 APC MLPA kit - 100 Reactions', 'PbP043-100R', 'MRC Holland', '0', False),
                                               ('SALSA P021 SMN MLPA kit - 100 Reactions', 'PbP021-100R', 'MRC Holland', '0', False),
                                               ('SALSA P010 POLG MLPA kit - 100 Reactions', 'PbP010-100R', 'MRC Holland', '0', False),
                                               ('SALSA P138 SLC2A1 MLPA kit - 50 Reactions', 'PbP138-50R', 'MRC Holland', '0', False),
                                               ('MgCl2 Solution~', 'BIO-37026', 'Scientific Laboratory Supplies', '2', False),
                                               ('SALSA ME030 BWS/RSS MLPA kit - 100 Reactions', 'ME030-100R', 'MRC Holland', '0', False),
                                               ('SALSA P008 PMS2 MLPA kit - 100 Reactions', 'PbP008-100R', 'MRC Holland', '0', False),
                                               ('SALSA P419 CDKN2A/B MLPA kit - 50 Reactions', 'PbP419-50R', 'MRC Holland', '0', False),
                                               ('SALSA P056 TP53 MLPA kit - 100 Reactions', 'PbP056-100R', 'MRC Holland', '0', False),
                                               ('SALSA P225 PTEN MLPA kit - 100 Reactions', 'PbP225-100R', 'MRC Holland', '0', False),
                                               ('MSI Analysis system', 'MD1641', 'Promega', '1', False),
                                               ('DIG Easy Hyb Granules', '11796895001', 'Sigma-Aldrich', '0', False),
                                               ('Dimethyl Sulfoxide~', 'D8418-50ml', 'Sigma-Aldrich', '0', False),
                                               ('Quantifluor dsDNA System~', 'E2670', 'Promega', '2', False),
                                               ('SALSA P089 TK2 MLPA kit - 50 Reactions', 'PbP089-50R', 'MRC Holland', '0', False),
                                               ('PhiX Control v3~', 'FC-110-3001', 'Illumina', '0', False),
                                               ('SALSA P235 Retinitis MLPA kit - 25 Reactions', 'PbP235-25R', 'MRC Holland', '0', False),
                                               ('SALSA P244 MEN1 MLPA kit - 100 Reactions', 'PbP244-100R', 'MRC Holland', '0', False),
                                               ('SALSA P231 LADD MLPA kit - 100 Reactions', 'PbP231-100R', 'MRC Holland', '0', False),
                                               ('STE Buffer Solution', '85810 - 100ml', 'Sigma-Aldrich', '0', False),
                                               ('SALSA P072 MSH6 MLPA kit - 50 Reactions', 'PbP072-50R', 'MRC Holland', '0', False),
                                               ('SALSA P034 DMD MLPA kit - 100 Reactions', 'PbP034-100R', 'MRC Holland', '0', False),
                                               ('SALSA P159 GLA MLPA kit - 50 Reactions', 'PbP159-50R', 'MRC Holland', '0', False),
                                               ('SALSA ME032 UPD7/UPD14 MLPA kit - 100 Reactions', 'ME032-100R', 'MRC Holland', '0', False),
                                               ('SALSA P035 DMD MLPA kit - 100 Reactions', 'PbP035-100R', 'MRC Holland', '0', False),
                                               ('ReliaPrep Large Volume HT gDNA Isolation System', 'A2751', 'Promega', '2', False),
                                               ('Maxwell RSC FFPE RNA kit', 'AS1440', 'Promega', '0', False),
                                               ('TE Buffer~', 'A2651', 'Promega', '0', False),
                                               ('CA Solution', '2CA25', 'Clent Life Science', '0', False),
                                               ('Megamix-Blue Double', '2MMBD-5', 'Clent Life Science', '0', False),
                                               ('SALSA P193 NPC1-NPC2-SMPD1 MLPA kit - 25 Reactions', 'PbP193-25R', 'MRC Holland', '0', False),
                                               ('KAPA Library Amplification Kit', '7958978001', 'Roche Diagnostic', '0', False),
                                               ('Tween 20~', 'P1379-250ml', 'Sigma-Aldrich', '0', False),
                                               ('KAPA LongRange', 'KK3602', 'Sigma-Aldrich', '0', False),
                                               ('GE Healthcare Deaza dGTP', '10146044', 'Fisher Scientific', '0', False),
                                               ('PrepIT Oragene Purifier', 'PT-L2P-5', 'DNA Genotek', '0', False),
                                               ('Proteinase K Solution~', 'A5051', 'Promega', '0', False),
                                               ('DNA Molecular Weight Marker II DIG-Labeled', '11218590910', 'Sigma-Aldrich', '0', False),
                                               ('Betaine', 'B2629-50g', 'Sigma-Aldrich', '0', False),
                                               ('SALSA P091 CFTR MLPA kit - 50 Reactions', 'PbP091-50R', 'MRC Holland', '0', False),
                                               ('SALSA P440 F10+F11 MLPA kit - 50 Reactions', 'PbP440-50R', 'MRC Holland', '0', False),
                                               ('SALSA P080 Cranio MLPA kit - 100 Reactions', 'PbP080-100R', 'MRC Holland', '0', False),
                                               ('SALSA P207 F9 MLPA kit - 50 Reactions', 'PbP207-50R', 'MRC Holland', '0', False),
                                               ('SALSA P479 TCF12-ERF MLPA kit - 100 Reactions', 'PbP479-100R', 'MRC Holland', '0', False),
                                               ('SALSA P158 JPS MLPA kit - 50 Reactions', 'PbP158-50R', 'MRC Holland', '0', False),
                                               ('SALSA P260 PALB2 MLPA kit - 25 Reactions', 'PbP260-25R', 'MRC Holland', '0', False),
                                               ('SALSA P112 PROS1 MLPA kit - 25 Reactions', 'PbP112-25R', 'MRC Holland', '0', False),
                                               ('SuRE/Cut Buffer A', '11417959001', 'Sigma-Aldrich', '0', False),
                                               ('CDP-Star', '12041677001', 'Sigma-Aldrich', '0', False),
                                               ('SALSA P178 F8 MLPA kit', 'PbP178-25R', 'MRC Holland', '0', False),
                                               ('SALSA P011 VWF-1 MLPA kit - 50 Reactions', 'PbP011-50R', 'MRC Holland', '0', False),
                                               ('SALSA P012 VWF-2 MLPA kit - 50 Reactions', 'PbP012-50R', 'MRC Holland', '0', False),
                                               ('Binding Buffer', 'A1741', 'Promega', '0', False),
                                               ('Cell Lysis Buffer', 'A1731', 'Promega', '0', False),
                                               ('SALSA P114 LQT MLPA kit - 100 Reactions', 'PbP114-100R', 'MRC Holland', '0', False),
                                               ('SALSA P347 Hemochromatosis MLPA kit - 100 Reactions', 'PbP347-100R', 'MRC Holland', '0', False),
                                               ('Ethidium Bromide Solution', 'E1510-10ML', 'Sigma-Aldrich', '0', False),
                                               ('SALSA P101 STK11 MLPA kit - 100 Reactions', 'PbP101-100R', 'MRC Holland', '0', False),
                                               ('SALSA P100 MYBPC3 MLPA kit - 100 Reactions', 'PbP100-100R', 'MRC Holland', '0', False),
                                               ('SALSA P469 F5 MLPA kit - 25 Reactions', 'PbP469-25R', 'MRC Holland', '0', False),
                                               ('SALSA P362 USH2A MIX 2 MLPA kit - 100 Reactions', 'PbP362-100R', 'MRC Holland', '0', False),
                                               ('SALSA P361 USH2A MIX 1 MLPA kit - 100 Reactions', 'PbP361-100R', 'MRC Holland', '0', False),
                                               ('Mineral Oil~', 'M5904-500ml', 'Sigma-Aldrich', '0', False),
                                               ('SALSA P441 SACs MLPA kit - 25 Reactions', 'PbP441-25R', 'MRC Holland', '0', False),
                                               ('SALSA P227 SERPINC1 MLPA kit - 25 Reactions', 'PbP227-25R', 'MRC Holland', '0', False),
                                               ('SALSA P166 KCNQ2 MLPA kit - 25 Reactions', 'PbP166-25R', 'MRC Holland', '0', False),
                                               ('dNTP set', 'BIO-39025', 'Scientific Laboratory Supplies', '0', False),
                                               ('SALSA P366 CHM-RP2-RPGR MLPA kit - 100 Reactions', 'PbP366-100R', 'MRC Holland', '0', False),
                                               ('BglII Restriction Enzyme', 'FD0083', 'Life Technologies', '0', False),
                                               ('SALSA P348 ATP1A2-CACNA1A MLPA kit - 25 Reactions', 'PbP348-25R', 'MRC Holland', '0', False),
                                               ('SALSA P418 MYH7 MLPA kit - 25 Reactions', 'PbP418-25R', 'MRC Holland', '0', False),
                                               ('SALSA P226 SDH MLPA kit - 25 Reactions', 'PbP226-25R', 'MRC Holland', '0', False),
                                               ('Orthoboric Acid~', '20185.36', 'VWR International', '0', False),
                                               ('SALSA P316 Recessive Ataxias MLPA kit - 50 Reactions', 'PbP316-50R', 'MRC Holland', '0', False),
                                               ('SALSA P432 MYH9 MLPA kit - 25 Reactions', 'PbP432-25R', 'MRC Holland', '0', False),
                                               ('Kapa HiFi Hot Start ReadyMIx', 'KK2602', 'Roche Diagnostic', '1', False),
                                               ('SALSA P265 PROC1 MLPA kit - 25 Reactions', 'PbP265-25R', 'MRC Holland', '0', False),
                                               ('SALSA P102 HBB MLPA ki - 100 Reactionst', 'PbP102-100R', 'MRC Holland', '1', False),
                                               ('SALSA P140 HBA MLPA kit - 100 Reactions', 'PbP140-100R', 'MRC Holland', '2', False),
                                               ('SALSA P212 DBA MLPA kit - 25 Reactions', 'PbP212-25R', 'MRC Holland', '0', False),
                                               ('SALSA P203 PKLR MLPA kit - 25 Reactions', 'PbP203-25R', 'MRC Holland', '0', False),
                                               ('SALSA PbP093 HHT/HPAH MLPA kit - 25 Reactions', 'PbP093-25R', 'MRC Holland', '0', False),
                                               ('SALSA PbP367 BEST1-PRPH2 MLPA kit - 25 Reactions', 'PbP367-25R', 'MRC Holland', '0', False),
                                               ('SALSA PbP062 LDLR MLPA kit - 100 Reactions', 'PbP062-100R', 'MRC Holland', '0', False),
                                               ('Twist Universal Adapter System - Plate A', '101308', 'TWIST Bioscience', '1', False),
                                               ('Twist Universal Adapter System - Plate B', '101309', 'TWIST Bioscience', '1', False),
                                               ('Twist Universal Adapter System - Plate C', '101310', 'TWIST Bioscience', '1', False),
                                               ('Twist Universal Adapter System  - Plate D', '101311', 'TWIST Bioscience', '1', False),
                                               ('SALSA P031 FANCA mix 1 MLPA Kit - 50 Reactions', 'PbP031-50R', 'MRC Holland', '0', False),
                                               ('SALSA P032 FANCA mix 2 MLPA Kit - 50 Reactions', 'PbP032-50R', 'MRC Holland', '0', False),
                                               ('Buffer EB~', '19086', 'Qiagen', '0', False),
                                               ('Formaldehyde~', '20910.294', 'VWR International', '0', False),
                                               ('QIAamp RNA Blood Mini Kit', '52304', 'Qiagen', '0', False),
                                               ('RNase-Free DNase Set', '79254', 'Qiagen', '0', False),
                                               ('PAXgene Blood RNA Kit', '762174', 'Qiagen', '0', False),
                                               ('BigDye Terminator v1.1 & v3.1 5X Sequencing Buffer', '4336699', 'Life Technologies', '1', False),
                                               ('HpyF3I Restriction Enzyme', 'FD1884', 'Life Technologies', '1', False),
                                               ('DraI Restriction Enzyme', 'ER0221', 'Life Technologies', '0', False),
                                               ('DS-33 Matrix Standard Kit (Dye Set G5)~', '4345833', 'Life Technologies', '0', False),
                                               ('SuperScript IV First-Strand Synthesis System', '18091200', 'Life Technologies', '0', False),
                                               ('Sodium Dodecyl Sulfate Solution~', '71736-500ML', 'Sigma-Aldrich', '0', False),
                                               ('PowerPlex 4C Matrix Standards~', 'DG4800', 'Promega', '0', False),
                                               ('Nylon MembraneS Positively Charged~', '11417240001', 'Sigma-Aldrich', '0', False),
                                               ('Twist Library Preparation EF kit 1', '100572', 'TWIST Bioscience', '3', False),
                                               ('Twist Universal Blocker', '100578', 'TWIST Bioscience', '3', False),
                                               ('Twist Hybridization Reagents', '100930', 'TWIST Bioscience', '3', False),
                                               ('Twist Binding and Purification Beads', '100983', 'TWIST Bioscience', '3', False),
                                               ('Twist Human Core Exome & RefSeq panel', '101920', 'TWIST Bioscience', '2', False),
                                               ('Twist Custom Panel', '101001', 'TWIST Bioscience', '2', False),
                                               ('Twist Library Preparation EF kit 2', '100573', 'TWIST Bioscience', '3', False),
                                               ('Twist Wash Buffers', '100985', 'TWIST Bioscience', '3', False),
                                               ('Ethanol Absolute', '20821.330DP', 'VWR International', '3', False),
                                               ('Custom Hereditary Cancer Solution', 'CS.2170.0102-00', 'Sophia Genetics', '3', False),
                                               ('Tri-Sodium Citrate~', '27833.294', 'VWR International', '0', False),
                                               ('Eco52I Restriction Enzyme', 'FD0334', 'Fisher Scientific', '0', False),
                                               ('Sodium Chloride~', '27810.364', 'VWR International', '0', False),
                                               ('SSC Buffer', '93017-10L-F', 'Sigma-Aldrich', '0', False),
                                               ('EcoRI Restriciton Enzyme', 'R0505S', 'Fisher Scientific', '0', False),
                                               ('Hydrochloric Acid~', '20252.244', 'VWR International', '0', False),
                                               ('Sodium Hydroxide Pellets', '8244.295', 'VWR International', '0', False),
                                               ('DEV-5 Dye Set Multicap~', '8-A401', 'Launch Diagnostics', '0', False),
                                               ('3730 DNA Analyzer Sequencing Standards BigDye Terminator v3.1~', '4336943', 'Life Technologies', '0', False),
                                               ('Sodium Hydroxide Solution', '10488790', 'Fisher Scientific', '0', False),
                                               ('2-Mercaptoethanol', 'M3148-25ml', 'Sigma-Aldrich', '0', False),
                                               ('MyFi Mix', 'BIO-25049', 'Scientific Laboratory Supplies', '1', False),
                                               ('GeneAmp 10X PCR Buffer II & MgCl2', 'N8080130', 'Life Technologies', '0', False)):
            values={}
            values["name"]=name
            values["cat_no"]=cata
            try:
                values["supplier_def"]=Suppliers.objects.get(name=sup)
            except Exception as e:
                print(e)
                print(sup)
                import pdb; pdb.set_trace()
            values["min_count"]=int(minimum)
            values["is_cyto"]=cyto
            try:
                Reagents.create(values)
            except Exception as e:
                print(e)
                print(name)
                import pdb; pdb.set_trace()
