# Generated by Django 2.2.6 on 2019-12-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0003_auto_20191204_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forcereset',
            options={'verbose_name_plural': 'Force Password Resets'},
        ),
    ]
