# Generated by Django 2.2.6 on 2019-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0004_auto_20191204_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcereset',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='fin_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Finished Reason'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='lot_no',
            field=models.CharField(max_length=50, verbose_name='Lot Number'),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
