# Generated by Django 2.2.6 on 2019-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0005_auto_20191213_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
