# Generated by Django 2.2.6 on 2019-12-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0006_suppliers_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internal',
            options={'verbose_name_plural': 'Stock Numbers'},
        ),
        migrations.AddField(
            model_name='reagents',
            name='is_cyto',
            field=models.BooleanField(default=False, verbose_name='Is this a FISH/CYTO Probe?'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_cyto',
            field=models.BooleanField(default=False, verbose_name='Is this a FISH/CYTO Probe Mix?'),
        ),
    ]
