# Generated by Django 2.2.6 on 2019-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0007_auto_20191216_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='vol_rec',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume Received (µl)'),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='is_cyto',
            field=models.BooleanField(default=False, verbose_name='Tick if this is a FISH/CYTO Probe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_cyto',
            field=models.BooleanField(default=False, verbose_name='Tick if this is a FISH/CYTO Probe Mix'),
        ),
    ]
