# Generated by Django 2.2.6 on 2019-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0008_auto_20191216_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='current_vol',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Volume (µl)'),
        ),
    ]
