# Generated by Django 2.2.6 on 2019-12-17 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_web', '0009_inventory_current_vol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CytoUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('used', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.Inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Volumes of FISH Probes Used',
            },
        ),
    ]
