# Generated by Django 2.2.6 on 2019-12-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0010_cytousage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cytousage',
            options={'verbose_name_plural': 'Cyto Reagent Usage'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.CytoUsage'),
        ),
    ]
