# Generated by Django 2.2.6 on 2019-12-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0011_auto_20191217_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagents',
            name='storage',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
