# Generated by Django 2.2.6 on 2019-12-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0014_reagents_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cytousage',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.Solutions'),
        ),
    ]
